version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce:12.5.1-ce.0
    hostname: 'xxxxxxxx.myqnapcloud.com:10080'
    container_name: gitlab
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - gitlab_config:/etc/gitlab:rw
      - gitlab_log:/var/log/gitlab:rw
      - gitlab_data:/var/opt/gitlab:rw
    environment:
      DEBUG: 'true'
      GITLAB_PORT: 10080
      GITLAB_SSH_PORT: 10022
      GITLAB_SECRETS_DB_KEY_BASE: qcs-gitlab-app
      GITLAB_SECRETS_OTP_KEY_BASE: qcs-gitlab-app
      GITLAB_SECRETS_SECRET_KEY_BASE: qcs-gitlab-app
      GITLAB_ROOT_EMAIL: xxxxxxxxxx@outlook.com
      GITLAB_BACKUP_SCHEDULE: weekly
      GITLAB_BACKUP_TIME: 01:00
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://xxxxxxxx.myqnapcloud.com:10080'
        unicorn['worker_timeout'] = 60
        unicorn['worker_processes'] = 2
        gitlab_rails['gitlab_shell_ssh_port'] = 23
        nginx['listen_port'] = 80
        user['git_user_email'] = "xxxxxxxxxx@outlook.com"
        gitlab_rails['initial_root_password'] = 'xxxxxxxxxx'
        gitlab_rails['webhook_timeout'] = 60
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.office365.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "xxxxxxxxxx@outlook.com"
        gitlab_rails['smtp_password'] = "xxxxxxxxx"
        gitlab_rails['smtp_domain'] = "smtp.office365.com"
        gitlab_rails['gitlab_email_from'] = "xxxxxxxxxx@outlook.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "10443:443"
    - "10022:22"
    # working_dir: '/share/CACHEDEV1_DATA/Container/gitlab'
    cpu_shares: 75
    mem_limit: 3072000000
    memswap_limit: 1024000000
    mem_reservation: 768m

  postgresql:
    container_name: gitlab_postgresql
    environment:
      DB_EXTENSION: pg_trgm
      DB_NAME: gitlabhq_production
      DB_PASS: vowkeeper911
      DB_USER: gitlab
    image: sameersbn/postgresql:10-2
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
  redis:
    container_name: gitlab_redis
    command:
    - --loglevel warning
    image: sameersbn/redis:latest
    restart: always
    volumes:
      - redis_data:/var/lib/redis:rw
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - 'runner_config:/etc/gitlab-runner'

volumes:
  gitlab_config:
    external: true
  gitlab_data:
    external: true
  gitlab_log:
    external: true
  redis_data:
    external: true
  postgres_data:
    external: true
  runner_config:
    external: true
